[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor Settings
monitor_speed = 115200

; Project Dependencies
lib_deps =
    adafruit/Adafruit TCS34725@^1.4.4
    Wire