[platformio]
build_dir = C:\tmp\pio_build

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit Fingerprint Sensor Library @ ^2.1.0
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.2
    makuna/RTC
    mobizt/Firebase ESP32 Client @ ^4.4.14
lib_archive = no