[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Matches the Serial.begin(115200) in your setup() for debugging
monitor_speed = 115200 

; Optional: Upload speed (speeds up the flashing process)
upload_speed = 921600